name: McDonaldPOS
options:
  bundleIdPrefix: com.jayyyden
  deploymentTarget: "16.0"
packages:
  SQLite:
    url: https://github.com/stephencelis/SQLite.swift.git
    from: 0.13.0
  SwiftyJSON:
    url: https://github.com/SwiftyJSON/SwiftyJSON.git
    from: 5.0.0
  Toast:
    url: https://github.com/scalessec/Toast-Swift
    from: 5.0.0
targets:
  McDonaldPOS:
    type: application
    platform: iOS
    sources: 
      - path: mcdonald POS
        excludes:
          - "**/*.storyboard"
          - "**/*.xib"
          - "controllers/**"
          - "cells/**"
          - "database/**"
          - "AppDelegate.swift"
          - "SceneDelegate.swift"
          - "Extension.swift"
    settings:
      base:
        SWIFT_VERSION: 5.0
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
    dependencies:
      - package: SQLite
      - package: SwiftyJSON
      - package: Toast
